project_id = "qfjgifubavuomwvroahy"

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-public-key]
verify_jwt = false

[functions.stripe-status]
verify_jwt = false

[functions.booking-expire-pending]
verify_jwt = false

[functions.captcha-verify]
verify_jwt = false

[functions.identity-webhook]
verify_jwt = false

