/**
 * Rules and terms — fully data-driven from the `rules` section of the
 * `common` namespace. No user-facing string lives in this file.
 */
import { useTranslation } from "react-i18next";
import { cancellationLadderBullets } from "@/lib/cancellationPolicyCopy";

/** Bullet list rendered from an i18n array key. */
function Bullets({ items }: { items: string[] }) {
  return (
    <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
      {items.map((line) => (
        <li key={line}>{line}</li>
      ))}
    </ul>
  );
}

export default function Regler() {
  const { t } = useTranslation("common");
  const translate = (key: string, vars: Record<string, string | number>) =>
    String(t(key, vars as never));
  const list = (key: string): string[] => {
    const value = t(key, { returnObjects: true }) as unknown;
    return Array.isArray(value) ? (value as string[]) : [];
  };

  return (
    <main className="container-wide py-12 max-w-3xl">
      <h1 className="font-heading text-4xl mb-3">{t("rules.heading")}</h1>
      <p className="text-muted-foreground mb-10">{t("rules.intro")}</p>

      <section className="space-y-8">
        <div>
          <h2 className="font-heading text-2xl mb-3">{t("rules.s1.title")}</h2>
          <Bullets items={list("rules.s1.items")} />
        </div>

        <div>
          <h2 className="font-heading text-2xl mb-3">{t("rules.s2.title")}</h2>
          <Bullets items={list("rules.s2.items")} />
        </div>

        <div>
          <h2 className="font-heading text-2xl mb-3">{t("rules.s3.title")}</h2>
          <p className="text-muted-foreground mb-3">{t("rules.s3.intro")}</p>
          {/* The ladder itself is generated by the canonical policy library so
              the page can never drift from the enforced cancellation rules. */}
          <Bullets items={[...cancellationLadderBullets(undefined, translate), ...list("rules.s3.afterBullets")]} />
        </div>

        <div>
          <h2 className="font-heading text-2xl mb-3">{t("rules.s4.title")}</h2>
          <Bullets items={list("rules.s4.items")} />
        </div>

        <div>
          <h2 className="font-heading text-2xl mb-3">{t("rules.s5.title")}</h2>
          <Bullets items={list("rules.s5.items")} />
        </div>

        <div>
          <h2 className="font-heading text-2xl mb-3">{t("rules.s6.title")}</h2>
          <p className="text-muted-foreground">{t("rules.s6.text")}</p>
        </div>

        <div>
          <h2 className="font-heading text-2xl mb-3">{t("rules.s7.title")}</h2>
          <p className="text-muted-foreground">{t("rules.s7.text")}</p>
        </div>
      </section>
    </main>
  );
}
