// This file is auto-generated by Lovable. Keep changes minimal and compatible.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

function normalizeRedirectUri(redirectUri?: string): string | undefined {
  if (!redirectUri || typeof window === "undefined") return redirectUri;

  try {
    const url = new URL(redirectUri, window.location.origin);

    // Google OAuth requires an exact redirect URI match. Production traffic can
    // arrive on both www.mycleaner.dk and mycleaner.dk, so always use the
    // canonical host while leaving Lovable previews and local development alone.
    if (url.hostname === "www.mycleaner.dk" || url.hostname === "mycleaner.dk") {
      url.protocol = "https:";
      url.hostname = "mycleaner.dk";
      url.port = "";
    }

    return url.toString();
  } catch {
    return redirectUri;
  }
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: normalizeRedirectUri(opts?.redirect_uri),
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
